on: pull_request
  branches:
    - master

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
  
